package:
  name: roq-cpp-algo-template
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CFLAGS=-O3                                                                                                                                                
    - CPPFLAGS=-O3  # [linux]                                                                                                                                   
    - CPPFLAGS=-O3 -D_LIBCPP_DISABLE_AVAILABILITY  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - rsync                                  # [build_platform != target_platform]
    - clang-format
    - cmake
    - make
    - roq-autogen
  host:
    - python {{ python }}
    - catch2
    - fmt
    - libabseil
    - pybind11
    - roq-algo
    - roq-api
    - roq-cache
    - roq-client
    - roq-flags
    - roq-logging
    - roq-market
    - roq-oss-benchmark
    - roq-oss-magic_enum
    - roq-oss-nameof
    - roq-oss-unordered_dense
    - roq-utils
    - tomlplusplus
  run:
    - python

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Roq C++ Algo Template (a template project)
