package:
  name: roq-algo-playground
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - CFLAGS=-O3                                                                                                                                                
    - CPPFLAGS=-O3  # [linux]                                                                                                                                   
    - CPPFLAGS=-O3 -D_LIBCPP_DISABLE_AVAILABILITY  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - clang-format
    - cmake
    - make
    - roq-autogen
  host:
    - catch2
    - fmt
    - libabseil
    - roq-algo
    - roq-api
    - roq-cache
    - roq-client
    - roq-flags
    - roq-logging
    - roq-market
    - roq-oss-benchmark
    - roq-oss-magic_enum
    - roq-oss-nameof
    - roq-oss-unordered_dense
    - roq-utils
    - tomlplusplus

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Roq C++ Algo Playground
