[[sources]]
  source=0
  market_data_latency=5ms
  order_management_latency=10ms
  [[accounts]]
    name="A1"
    [[symbols]]
      exchange="deribit"
      symbol="BTC-PERPETUAL"
      long_position=3

[[sources]]
  source=1
  market_data_latency=175ms
  order_management_latency=180ms
  [[accounts]]
    name="A1"
    [[symbols]]
      exchange="bybit"
      symbol="BTCUSD"
      short_position=3
