type="arbitrage"

[[legs]]
  source=0
  account="A1"
  exchange="deribit"
  symbol="BTC-PERPETUAL"
  time_in_force="gtc"

[[legs]]
  source=1
  account="A1"
  exchange="bybit"
  symbol="BTCUSD"
  time_in_force="gtc"
